Repository endless-sky/Endless-Sky-Delta, pull requests merged in 2024-11, with the labels that each got.

#121 Feat(code): Converting pylon to missile pylon for ease of understanding
  data/_deprecated/deprecated outfits.txt
  data/_ui/tooltips.txt
  data/bunrodea/bunrodea weapons.txt
  data/coalition/coalition weapons.txt
  data/hai/hai outfits.txt
  data/human/weapons.txt
  data/incipias/incipias outfits.txt
  data/kahet/kahet outfits.txt
  data/korath/korath weapons.txt
  data/pug/pug outfits.txt
  data/remnant/remnant outfits.txt
  data/sheragi/sheragi outfits.txt
  data/successors/successor weapons.txt
  data/wanderer/wanderer outfits.txt
  source/Armament.cpp
  source/Hardpoint.h
  source/HardpointInfoPanel.cpp
  source/OutfitInfoDisplay.cpp
  source/OutfitterPanel.cpp
  source/PrintData.cpp
  source/Ship.cpp
  source/ShipInfoDisplay.cpp
Labels: UI, Content (data), code

#124 feat(update): 2024-11-03 Conflict Resolution
  .github/workflows/cd.yaml
  .github/workflows/cd_release.yaml
  .github/workflows/ci.yml
  data/starts.txt
  vcpkg-configuration.json
Labels: Updating

#126 Feat(update): 2024 11 06conflict
  data/starts.txt
  source/GameAction.cpp
  source/GameAction.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/StartConditions.cpp
  source/StartConditions.h
Labels: Updating

#128 Feat(update): 2024-11-06 Second conflict update (same spot: Hai Start)
  .editorconfig
  data/_ui/tooltips.txt
  data/globals.txt
  data/starts.txt
  source/Outfit.cpp
  source/ShipJumpNavigation.cpp
  source/ShipJumpNavigation.h
Labels: Updating

#131 New uninhabited planet: Donya
  data/map planets.txt
  data/map systems.txt
Labels: Content (data)

#130 A few bug fixes in the Thermal Scanner missions
  data/governments.txt
  data/human/free worlds side plots.txt
  data/human/hails.txt
Labels: bug, Content (data)

#125 fix(bug): hostilize Korath mission spawns
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant 2 side missions.txt
Labels: bug, Content (data)

#123 feat(data): Hyperjump fuel cost varies by mass
  copyright
  data/_deprecated/deprecated ships.txt
  data/_ui/interfaces.txt
  data/bunrodea/bunrodea ships.txt
  data/categories.txt
  data/coalition/coalition ships.txt
  data/drak/drak ships.txt
  data/drak/indigenous.txt
  data/gegno/gegno ships.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai ships.txt
  data/human/hud outfits.txt
  data/human/kestrel.txt
  data/human/marauders.txt
  data/human/outfits.txt
  data/human/sales.txt
  data/human/ships.txt
  data/incipias/incipias ships.txt
  data/kahet/kahet ships.txt
  data/korath/korath ships.txt
  data/persons.txt
  data/pug/pug ships.txt
  data/quarg/quarg ships.txt
  data/remnant/remnant ships.txt
  data/remnant/remnant.txt
  data/starts.txt
  data/successors/successor ships.txt
  data/vyrmeid/vyrmeid.txt
  data/wanderer/wanderer ships.txt
  images/outfit/cockpit hyperjump software.png
  images/outfit/cockpit hyperjump software@2x.png
  images/outfit/cockpit jumpdrive software.png
  images/outfit/cockpit jumpdrive software@2x.png
  images/outfit/cockpit mass software.png
  images/outfit/cockpit mass software@2x.png
  images/outfit/cockpit scramjump software.png
  images/outfit/cockpit scramjump software@2x.png
  images/outfit/cockpit software.png
  images/outfit/cockpit software@2x.png
  images/ui/tactical/hyperjump.png
  images/ui/tactical/hyperjump@2x.png
  images/ui/tactical/jumpdrivejump.png
  images/ui/tactical/jumpdrivejump@2x.png
  images/ui/tactical/mass.png
  images/ui/tactical/mass@2x.png
  images/ui/tactical/scramjump.png
  images/ui/tactical/scramjump@2x.png
  source/Engine.cpp
  source/Ship.cpp
  source/Ship.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_wormhole_navigation.txt
Labels: enhancement, Content (data), code

#134 feat(data): Creating the Random Author Disco Ball Person
  data/persons.txt
Labels: Content (data)

#140 Feat(updated): 2024-11-15 conflict resolution
  .codespell.exclude
  data/successors/successor events.txt
  data/successors/successor hails.txt
  data/successors/successor side missions.txt
  data/successors/successors.txt
  source/Engine.cpp
  source/Information.cpp
  source/Information.h
  source/Interface.cpp
Labels: Updating

#142 Feat(update): 2024-11-16 updating
  data/human/human missions.txt
  source/AI.cpp
  source/ConditionSet.cpp
  source/ConditionsStore.cpp
  source/DataNode.cpp
  source/DataNode.h
  source/DistanceMap.cpp
  source/DistanceMap.h
  source/GameEvent.cpp
  source/Mission.cpp
  source/Outfit.cpp
  source/Outfit.h
Labels: Updating

#146 Feat(update): 2024-11-22 conflict resolution
  .codespell.exclude
  .codespell.words.exclude
  data/_ui/help.txt
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  data/bunrodea/bunrodea ships.txt
  data/gegno/gegno.txt
  data/globals.txt
  data/governments.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai ships.txt
  data/human/free worlds 4 epilogue.txt
  data/human/human missions.txt
  data/human/ships.txt
  data/incipias/incipias ships.txt
  data/map planets.txt
  source/MenuPanel.cpp
Labels: Updating

#149 feat(update):2024-11-24
  data/remnant/remnant 1 introduction.txt
  source/CMakeLists.txt
  source/ConditionAssignments.cpp
  source/ConditionAssignments.h
  source/ConditionSet.cpp
  source/ConditionSet.h
  source/Conversation.cpp
  source/Date.cpp
  source/GameAction.h
  source/GameEvent.cpp
  source/GameEvent.h
  source/Mission.cpp
  source/StartConditions.cpp
  source/StartConditions.h
  source/TextReplacements.cpp
  source/test/Test.cpp
  source/test/Test.h
  tests/CMakeLists.txt
  tests/unit/src/test_conditionAssignments.cpp
  tests/unit/src/test_conditionSet.cpp
Labels: Updating

#147 feat(data): Replacing small killer pirate variants with new variants better suited to looting
  data/human/fleets.txt
  data/human/variants.txt
Labels: bug, Content (data)

#153 feat(update): 2024-11-25 partial update to take care of some of the extraneous commmits
  .codespell.exclude
  data/human/deep missions.txt
  data/human/human missions.txt
  data/remnant/remnant 2 side missions.txt
  data/remnant/remnant jobs.txt
  data/successors/successor 1 prologue.txt
  data/successors/successor side missions.txt
  source/AI.cpp
  source/BatchDrawList.cpp
  source/Body.cpp
  source/Body.h
  source/DrawList.cpp
  source/MenuPanel.cpp
  source/MenuPanel.h
  source/PlanetLabel.cpp
  source/PlanetLabel.h
  source/System.cpp
  source/audio/Audio.cpp
  source/audio/Audio.h
  source/main.cpp
Labels: Updating

#152 feat(update):2024-11-25 Conflict Update
  .editorconfig
  .github/workflows/ci.yml
  CMakePresets.json
  overlays/macos-arm64-ci.cmake
  source/BankPanel.cpp
  source/BoardingPanel.cpp
  source/HailPanel.cpp
  source/HardpointInfoPanel.cpp
  source/HardpointInfoPanel.h
  source/HiringPanel.cpp
  source/Information.cpp
  source/Information.h
  source/Interface.cpp
  source/LoadPanel.cpp
  source/MapPanel.cpp
  source/MenuPanel.cpp
  source/MessageLogPanel.cpp
  source/MissionAction.cpp
  source/MissionPanel.cpp
  source/Panel.cpp
  source/Panel.h
  source/PlanetPanel.cpp
  source/PlayerInfoPanel.cpp
  source/PreferencesPanel.cpp
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
  source/StartConditionsPanel.cpp
  source/StartConditionsPanel.h
  source/TradingPanel.cpp
  utils/check_copyright.py
  utils/korath-cipher.py
  vcpkg-configuration.json
  vcpkg.json
Labels: Updating

#155 fix(bug): less than a year -> just over a year
  data/human/campaign events.txt
Labels: bug
