Repository endless-sky/Endless-Sky-Delta, pull requests merged in 2024-03, with the labels that each got.

#38 Fix load menu "back to menu" button
  data/_ui/interfaces.txt
Labels: bug, UI

#43 feat(fix): Fixing the discrepancy between the Settings panel sprite and the infoTable text
  data/_ui/interfaces.txt
  source/PreferencesPanel.cpp
Labels: bug

#44 feat(fix): Fixing the gimbal to work properly in some situation
  source/Engine.cpp
  source/Ship.cpp
Labels: bug

#34 feat(balance): Adjusting mass, thrust, and turning across all ships
  data/_deprecated/deprecated ships.txt
  data/bunrodea/bunrodea outfits.txt
  data/bunrodea/bunrodea ships.txt
  data/categories.txt
  data/coalition/coalition outfits.txt
  data/coalition/coalition ships.txt
  data/drak/drak ships.txt
  data/gegno/gegno outfits.txt
  data/gegno/gegno ships.txt
  data/hai/hai outfits.txt
  data/hai/hai reveal 1 intro.txt
  data/hai/hai ships.txt
  data/human/engines.txt
  data/human/kestrel.txt
  data/human/marauders.txt
  data/human/ships.txt
  data/kahet/kahet outfits.txt
  data/kahet/kahet ships.txt
  data/korath/korath outfits.txt
  data/korath/korath ships.txt
  data/persons.txt
  data/pug/pug outfits.txt
  data/pug/pug ships.txt
  data/quarg/quarg outfits.txt
  data/quarg/quarg ships.txt
  data/remnant/remnant outfits.txt
  data/remnant/remnant ships.txt
  data/rulei/rulei ships.txt
  data/sheragi/sheragi outfits.txt
  data/sheragi/sheragi ships.txt
  data/wanderer/wanderer outfits.txt
  data/wanderer/wanderer ships.txt
Labels: help wanted, balance
