Repository endless-sky/Endless-Sky-Delta, pull requests merged in 2024-12, with the labels that each got.

#159 feat(update): 2024 12 02 b1 Don't generate key presses revert and Use AA instead of aa
  data/human/human missions.txt
  source/BankPanel.cpp
  source/BoardingPanel.cpp
  source/HailPanel.cpp
  source/HardpointInfoPanel.cpp
  source/HardpointInfoPanel.h
  source/HiringPanel.cpp
  source/Information.cpp
  source/Information.h
  source/Interface.cpp
  source/LoadPanel.cpp
  source/MapPanel.cpp
  source/MenuPanel.cpp
  source/MessageLogPanel.cpp
  source/MissionPanel.cpp
  source/Panel.cpp
  source/Panel.h
  source/PlanetPanel.cpp
  source/PlayerInfoPanel.cpp
  source/PreferencesPanel.cpp
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
  source/StartConditionsPanel.cpp
  source/StartConditionsPanel.h
  source/TradingPanel.cpp
Labels: Updating

#160 feat(update): 2024-12-02-b2 Updating part 2
  SConstruct
  tests/integration/config/plugins/integration-tests/data/disabling troublesome missions.txt
Labels: Updating

#162 feat(update): 2024 11 02 conflict update
  tests/integration/IntegrationTests.cmake
Labels: Updating

#156 Feat(code): Fixes the ship info and Hardpoint tooltip system to work again.
  data/_ui/tooltips.txt
  source/ItemInfoDisplay.cpp
  source/LoadPanel.cpp
  source/MapPanel.cpp
  source/MissionPanel.cpp
  source/PreferencesPanel.cpp
  source/ShipInfoDisplay.cpp
  source/ShopPanel.cpp
Labels: bug, Content (data), code

#163 feat(update): 2024-12-02 C - Remove extra tabs from two human missions (#10834)
  data/human/human missions.txt
Labels: Updating

#171 12/08/24 conflict update
  copyright
  data/human/campaign events.txt
  data/human/deep missions.txt
  data/human/fleets.txt
  data/human/free worlds 0 prologue.txt
  data/human/free worlds 1 start.txt
  data/human/free worlds 2 middle.txt
  data/human/free worlds 3 checkmate.txt
  data/human/free worlds 3 reconciliation.txt
  data/human/free worlds side plots.txt
  data/human/human missions.txt
  data/human/pirate jobs.txt
  data/human/ships.txt
  data/human/variants.txt
  data/wanderer/wanderers middle.txt
  data/wanderer/wanderers start.txt
  images/ship/carrier.png
  images/ship/modified carrier.png
  images/thumbnail/carrier.png
  images/thumbnail/modified carrier.png
Labels: Updating

#175 feat(update): 2024-12-11
  data/_ui/interfaces.txt
  data/kahet/kahet missions.txt
  source/OutfitterPanel.cpp
Labels: Updating

#166 Feat(code): Update UI for current system
  data/_ui/interfaces.txt
  images/ui/current system.png
  source/Engine.cpp
Labels: enhancement, UI

#181 feat(update): 2024-12-15 General Update
  data/_ui/interfaces.txt
  data/korath/korath missions.txt
  data/remnant/remnant 1 introduction.txt
  data/remnant/remnant 2 cognizance.txt
  data/remnant/remnant events.txt
  source/Command.cpp
  source/Command.h
  source/ConversationPanel.cpp
  source/DataFile.cpp
  source/DataFile.h
  source/DataWriter.cpp
  source/DataWriter.h
  source/Engine.cpp
  source/Engine.h
  source/File.cpp
  source/File.h
  source/Files.cpp
  source/Files.h
  source/GameData.cpp
  source/GameData.h
  source/GameWindow.cpp
  source/LoadPanel.cpp
  source/LoadPanel.h
  source/MapPanel.cpp
  source/MapPanel.h
  source/MenuPanel.cpp
  source/Mission.cpp
  source/Mission.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
  source/Plugins.cpp
  source/Plugins.h
  source/Preferences.cpp
  source/PreferencesPanel.cpp
  source/SavedGame.cpp
  source/SavedGame.h
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  source/audio/Audio.cpp
  source/audio/Audio.h
  source/audio/Music.cpp
  source/audio/Music.h
  source/audio/Sound.cpp
  source/audio/Sound.h
  source/image/ImageSet.cpp
  source/main.cpp
  source/test/TestData.cpp
  source/test/TestData.h
  source/text/Font.cpp
  source/text/Font.h
  source/text/FontSet.cpp
  source/text/FontSet.h
Labels: Updating

#167 Feat(code): Add Intrasolar ship category & update flight check
  data/categories.txt
  source/PlayerInfo.cpp
  source/Ship.cpp
Labels: enhancement

#182 Feat(update): 2024-12-16 conflict update (includes Strategic Scanning capabilities)
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  source/Engine.cpp
  source/Files.cpp
  source/Ship.h
  source/ShopPanel.cpp
  source/ship/ShipAICache.cpp
  source/ship/ShipAICache.h
Labels: Updating

#183 feat(update): 2024-12-19 Code & test framework
  source/Dialog.cpp
  source/TextArea.cpp
  source/TextArea.h
  source/test/Test.cpp
  source/test/Test.h
  source/text/WrappedText.cpp
  source/text/WrappedText.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_afterburn_flight.txt
Labels: Updating

#186 Feat(update): 2024-12-22 update requiring careful handling due to removal of erase breaking the compilation
  data/map systems.txt
  source/ConditionsStore.cpp
  source/ConditionsStore.h
  source/PlayerInfo.cpp
  tests/unit/src/test_conditionsStore.cpp
Labels: bug, Updating, code
