Repository endless-sky/Endless-Sky-Delta, pull requests merged in 2025-02, with the labels that each got.

#190 feat(code): Permanent changes to the player's ship via conversation actions.
  data/korath/korath ships.txt
  data/korath/korath variants.txt
  data/persons.txt
  source/GameAction.cpp
  source/GameAction.h
  source/Outfit.cpp
  source/Outfit.h
  source/Ship.cpp
  source/Ship.h
Labels: enhancement, code

#194 Remove Particle Cannons from Syndicate, Civillian Fleets
  data/human/fleets.txt
  data/human/ships.txt
  data/human/variants.txt
Labels: balance, Content (data)

#164 Feat(code): Add HUD display for Solar Power and Solar Wind
  copyright
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  data/human/outfits.txt
  data/human/sales.txt
  images/ui/tactical/wind.png
  source/Engine.cpp
  source/Ship.cpp
  source/Ship.h
Labels: enhancement, code

#206 feat(update): 2025-02-02
  data/human/deep missions.txt
  data/human/human missions.txt
  source/AI.cpp
  source/BoardingPanel.cpp
  source/PlayerInfo.cpp
  source/ShipInfoPanel.cpp
  source/ShipNameDialog.cpp
  source/text/WrappedText.cpp
Labels: Updating

#207 feat(fix): Fixing the Settings panel alignment
  data/_ui/interfaces.txt
Labels: bug

#208 feat(c): Starry Map cleanup
  data/_ui/interfaces.txt
  source/MapPanel.cpp
  source/MapPanel.h
  source/PlayerInfo.cpp
  source/PlayerInfo.h
Labels: UI, code

#195 feat(data): Scaling Drones 40%, Fighters 50%, Interceptors 60%
  data/_deprecated/deprecated ships.txt
  data/bunrodea/bunrodea ships.txt
  data/coalition/coalition ships.txt
  data/gegno/gegno ships.txt
  data/hai/hai ships.txt
  data/human/human missions.txt
  data/human/ships.txt
  data/kahet/kahet ships.txt
  data/korath/korath ships.txt
  data/persons.txt
  data/remnant/remnant ships.txt
  data/sheragi/sheragi ships.txt
  data/successors/successor ships.txt
  data/wanderer/wanderer ships.txt
Labels: good first issue, help wanted, balance, Content (data)

#209 Feat(data): Add Formations To Human Fleets
  data/human/fleets.txt
Labels: Content (data)

#212 Feat(update): 2025-02-06 update
  data/avgi/avgi news.txt
  data/avgi/avgi side missions.txt
  data/hai/hai culture conversations.txt
  data/hai/hai reveal 0 prologue.txt
  data/human/deep missions.txt
  data/human/ships.txt
  data/map planets.txt
  data/remnant/remnant 1 introduction.txt
Labels: Updating

#211 feat(fix): Fixing Lateral Thruster usage
  source/AI.cpp
Labels: bug, code

#214 fix(content): Added a missing passengers line to the Human to Hai Spa…
  data/human/human missions.txt
Labels: Updating

#213 Feat(data): tutorial engine mod
  data/categories.txt
  data/human/engines.txt
  data/human/intro missions.txt
Labels: Content (data)

#217 Feat(code): 2025-02-08 conflict update
  data/_ui/interfaces.txt
  data/_ui/tooltips.txt
  data/human/weapons.txt
  source/MapPanel.cpp
Labels: Updating

#218 feat(update): 2025-02-11 No conflict update.
  data/map planets.txt
  data/map systems.txt
  source/Ship.cpp
  source/Weapon.h
Labels: Updating

#216 Feat(data): Removing forced universal reverse thruster
  data/_deprecated/deprecated outfits.txt
  data/bunrodea/bunrodea outfits.txt
  data/coalition/coalition outfits.txt
  data/gegno/gegno outfits.txt
  data/hai/hai outfits.txt
  data/human/engines.txt
  data/kahet/kahet outfits.txt
  data/korath/korath outfits.txt
  data/pug/pug outfits.txt
  data/quarg/quarg outfits.txt
  data/sheragi/sheragi outfits.txt
  data/wanderer/wanderer outfits.txt
  data/whispering void/critters.txt
Labels: Content (data)

#122 feat(code): Custom outfit prices and sell type
  data/_ui/tooltips.txt
  data/custom sales.txt
  source/CMakeLists.txt
  source/CustomSale.cpp
  source/CustomSale.h
  source/CustomSaleManager.cpp
  source/CustomSaleManager.h
  source/Depreciation.cpp
  source/GameData.cpp
  source/GameData.h
  source/GameEvent.cpp
  source/MapOutfitterPanel.cpp
  source/MapSalesPanel.cpp
  source/MapShipyardPanel.cpp
  source/OutfitterPanel.cpp
  source/PlayerInfo.cpp
  source/ShopPanel.cpp
  source/UniverseObjects.cpp
  source/UniverseObjects.h
  tests/integration/config/plugins/integration-tests/data/tests/tests_common.txt
Labels: enhancement

#219 feat(data): Adding slots to the Avgi
  data/avgi/avgi outfits.txt
  data/avgi/avgi ships.txt
Labels: bug, Content (data)

#221 Feat(data): Revising the alt text for the destroyed blockade in Cognizance 29
  data/remnant/remnant 2 cognizance.txt
Labels: Content (data)

#222 feat(update): Updating version number to 0.10.11.6
  CMakeLists.txt
  credits.txt
  endless-sky.6
  source/main.cpp
Labels: Updating

#224 Feat(update):2025-02-21 conflict update
  .codespell.exclude
  .github/workflows/ci.yml
  data/avgi/avgi 0 first contact.txt
  data/avgi/avgi culture conversations.txt
  data/avgi/avgi fleets.txt
  data/avgi/avgi jobs.txt
  data/avgi/avgi news.txt
  data/avgi/avgi outfits.txt
  data/avgi/avgi ships.txt
  data/avgi/avgi side missions.txt
  data/avgi/avgi weapons.txt
  data/avgi/avgi.txt
  data/coalition/lunarium intro.txt
  data/governments.txt
  data/human/free worlds 3 reconciliation.txt
  data/human/human missions.txt
  data/kahet/aberrant outfits.txt
  data/kahet/aberrant ships.txt
  data/kahet/aberrant.txt
  data/map planets.txt
  data/map systems.txt
  data/remnant/remnant jobs.txt
  data/wanderer/wanderers start.txt
  endless-sky.6
  source/ShipInfoPanel.cpp
  source/ShipInfoPanel.h
  source/audio/Audio.cpp
  source/audio/Audio.h
  source/main.cpp
Labels: Updating

#226 Feat(update): 2025 02 23 conflict update
  CMakeLists.txt
  changelog
  credits.txt
  data/_ui/interfaces.txt
  data/avgi/avgi outfits.txt
  data/dialog phrases.txt
  data/globals.txt
  data/hai/hai missions.txt
  data/hai/hai reveal 1 intro.txt
  data/human/jobs.txt
  data/human/news.txt
  data/human/ships.txt
  data/human/variants.txt
  data/kahet/aberrant missions.txt
  data/kahet/kahet missions.txt
  data/wanderer/wanderers start.txt
  endless-sky.6
  io.github.endless_sky.endless_sky.appdata.xml
  resources/EndlessSky-Info.plist
  source/Command.cpp
  source/ConditionAssignments.cpp
  source/ConditionAssignments.h
  source/ConditionSet.cpp
  source/ConditionSet.h
  source/Dialog.cpp
  source/Engine.cpp
  source/PlayerInfoPanel.cpp
  source/main.cpp
  tests/integration/config/plugins/integration-tests/data/tests/tests_spawn_limits.txt
  tests/unit/src/test_conditionAssignments.cpp
  tests/unit/src/test_conditionSet.cpp
Labels: Updating

#229 feat(data): Emerald Sword update adding jump mass cost 3 base 1800 and fuel to 5475
  data/sheragi/sheragi outfits.txt
  data/sheragi/sheragi ships.txt
Labels: bug, Content (data)
